### ISSUE TITLE
@DBUnit with @SingleExecution extension execution order not preserving

### ISSUE THREAD

**Issue by Kanti1702** [janbols/spock-dbunit#11]
I'm trying to use @DbUnit at field level, and @SingleExecution at method level.

Issue: @DbUnit should be execute first and then @SingleExecution should be execute

For @SingleExecution - interceptIterationExecution() contain logic which every time first executed
For @DbUnit - interceptFeatureMethod() contain logic which executed after @SingleExecution interceptIterationExecution method execute.

Currently they are executing in below order:
1. @SingleExecution
2. @DbUnit
3. My feature/spec execution

But I want to execute above annotation in following order:
1. @DbUnit - 
2. @SingleExecution
3. My feature/spec execution

My code is as below:
@DbUnit(configure={ IDatabaseTester it ->
        it.setUpOperation = InsertIdentityOperation.REFRESH
        it.tearDownOperation = InsertIdentityOperation.NONE
    })
    def content =  {
       table1(col1:value1, col2:value2)
   }

  @SingleExecution('getColumnWiseMap')
  def "test data table with single execution"(){
     .....
  }

  def getColumnWiseMap(){
     return ....;
  }

**Comment by janbols** [comment]
Hi @Kanti1702 ,
I'm afraid this extension is not compatible with https://github.com/sjurgemeyer/spock-extensions 's extension (I'm assuming you're talking about that one). 

It's my impression that `@SingleExecution` is only used for data driven tests where you have several iterations of the same test with different data. That extension hooks in at an earlier lifecycle, specifically for data driven tests, than the `DbUnit` extension. That's why it's executed first. There's not a lot we can do to change this except play with the different lifecycle hooks.

Howver, my advise to you is to not rely too much on special extensions like this one or the one for `@SingleExection`. These things tend to work for the given use case but break easily when you want to combine them with other extensions.

Good luck
